### PR TITLE
solve issue with dbshell asking for password

### PR DESCRIPTION
**Pull request by Fiedzia**

### CODE REVIEW

**Comment by ashchristopher** [comment]
Change looks good. Can you bump the version (to 0.0.3), and update the `HISTORY.rst`? Then feel free to add your information to the `CONTRIBUTERS.rst` file.

Thanks!

**Comment by Fiedzia** [comment]
Done

**Comment by ashchristopher** [comment]
@Fiedzia I just tested this PR, and I don't think this is adding any more functionality than the original. See https://github.com/django/django/blob/master/django/db/backends/postgresql_psycopg2/client.py#L9-L19

By default, it will pull the `USER`, `HOST`, `PORT` and `NAME` off of the settings_dict and pass in as arguments.

**Comment by Fiedzia** [comment]
The difference is that I am running pgcli within existing process, instead of creating new one.
This way it is safe to pass password, which is what I am missing from default implementation.

**Comment by ashchristopher** [comment]
I am not sure yet how I feel about straying from how Django handles this. Take a look at the conversation in this ticket: https://code.djangoproject.com/ticket/7554

How are you passing in the password? I don't see you pulling the password out of `settings_dict` and passing to the cli.

**Pull request closed without merging**
